data:
  root: data
  actions: interim/actions
  scenes: interim/scenes
  csv_kpoints: processed/scenes  

  auto_labeling: processed/auto_labeling
  debug_actions: debug/actions # for debugging
  debug_scenes: debug/scenes
  test: data/test
  train: data/train

data_EC2:
  root: data
  actions: interim/actions
  auto_labeling: processed/auto_labeling # to store CSV's with keypoints

S3:
  bucket_name: hanball
  actions: actions/
  auto_labeling: auto_labeling/



classes:
  0: crossing
  1: defence
  2: dribbling
  3: jump-shot
  4: passing
  5: running
  6: shot

models:
  detection: models/yolov8n.pt
  pose: models/yolov8n-pose.pt
  pose_gpu: models/yolo8x-pose-p6.pt  

keypoints:
  coco_pairs:
    # - [0, 1],  # nose to left_eye
    # [0, 2],  # nose to right_eye
    # [1, 3],  # left_eye to left_ear
    # [2, 4],  # right_eye to right_ear
    - [5, 6]   # left_shoulder to right_shoulder
    - [5, 7]   # left_shoulder to left_elbow
    - [6, 8]   # right_shoulder to right_elbow
    - [7, 9]   # left_elbow to left_wrist
    - [8, 10]  # right_elbow to right_wrist
    - [5, 11]  # left_shoulder to left_hip
    - [6, 12]  # right_shoulder to right_hip
    - [11, 12] # left_hip to right_hip
    - [11, 13] # left_hip to left_knee
    - [12, 14] # right_hip to right_knee
    - [13, 15] # left_knee to left_ankle
    - [14, 16] # right_knee to right_ankle


